export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

// POSTS
export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';

// BLOGS
export const BLOG_LOADING = 'BLOG_LOADING';
export const GET_BLOGS = 'GET_BLOGS';
export const GET_BLOG = 'GET_BLOG';
export const ADD_BLOG = 'ADD_BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';


// PROFILE IMAGE UPLOAD
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAIL = 'UPLOAD_DOCUMENT_FAIL';

// FRIENDS
export const ADD_FRIEND = 'ADD_FRIEND';
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';
export const GET_ALL_FRIENDS = 'GET_ALL_FRIENDS';

// CHAT TYPES
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_RECIEVED = 'MESSAGE_RECIEVED';
export const ADD_USER = 'ADD_USER';
export const USERS_LIST = 'USERS_LIST';

// EMAIL TYPES
export const SEND_EMAIL = 'SEND_EMAIL';
export const GET_ALL_MAILS = 'GET_ALL_MAILS';
export const GET_MAIL_BY_ID = 'GET_MAIL_BY_ID';



export const GET_REQUESTS = 'GET_REQUESTS';

